export const FETCH_TASKS = 'lists/FETCH_TASKS'
export const SET_TASKS_TO_LIST = 'lists/SET_TASKS_TO_LIST'
export const SET_LISTS = 'lists/SET_LISTS'
export const ADD_NEW_LIST = 'lists/ADD_NEW_LIST'
export const ADD_NEW_TASK = 'lists/ADD_NEW_TASK'
export const ADD_TASK = 'lists/ADD_TASK'
