export const ADD_PROJECTS = 'projects/ADD_PROJECTS'
export const ADD_PROJECT = 'projects/ADD_PROJECT'
export const UPSERT_PROJECT = 'projects/ADD_PROJECT'
export const UPDATE_PROJECT = 'projects/UPDATE_PROJECT'
export const UPDATE_PROJECT_ATTRIBUTE = 'projects/UPDATE_PROJECT_ATTRIBUTE'
export const DELETE_PROJECT = 'projects/DELETE_PROJECT'
